"""Alert engine (Requirement 14).

Alerts are generated by the system when a *threshold or state change* is
detected - never by asking a language model whether something seems urgent.
Conditions are evaluated against the live operational picture, so the same
check produces an alert once and then stays quiet until the underlying
condition clears (deduplicated by ``(alert_type, incident_id, context_key)``).
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select

from app.models.enums import AlertSeverity, AlertType, RouteStatus
from app.models.models import Alert

logger = logging.getLogger(__name__)

__all__ = ["AlertService"]


class AlertService:
    def __init__(self, session) -> None:
        self.session = session

    # -- queries ------------------------------------------------------------

    async def list_alerts(
        self, active_only: bool = False, unacknowledged_only: bool = False,
        limit: int = 100,
    ) -> list[Alert]:
        stmt = select(Alert).order_by(Alert.created_at.desc()).limit(limit)
        if active_only:
            stmt = stmt.where(Alert.is_active.is_(True))
        if unacknowledged_only:
            stmt = stmt.where(Alert.acknowledged.is_(False))
        return list((await self.session.scalars(stmt)).all())

    async def get(self, alert_id: str) -> Alert | None:
        return await self.session.scalar(
            select(Alert).where(Alert.alert_id == alert_id)
        )

    async def active_count(self) -> int:
        alerts = await self.list_alerts(active_only=True, unacknowledged_only=True)
        return len(alerts)

    # -- creation -----------------------------------------------------------

    async def raise_alert(
        self,
        alert_type: AlertType,
        message: str,
        *,
        severity: AlertSeverity = AlertSeverity.WARNING,
        incident_id: str | None = None,
        context: dict[str, Any] | None = None,
        context_key: str | None = None,
    ) -> Alert | None:
        """Create an alert, or return None if an identical one is already active."""
        key = context_key or _derive_key(alert_type, incident_id, context)

        existing = await self.session.scalar(
            select(Alert).where(
                Alert.alert_type == alert_type.value,
                Alert.incident_id == incident_id,
                Alert.is_active.is_(True),
                Alert.message == message,
            )
        )
        if existing is not None:
            logger.debug("Alert suppressed (already active): %s", message)
            return None

        alert = Alert(
            alert_id=f"ALT-{uuid.uuid4().hex[:8].upper()}",
            incident_id=incident_id,
            alert_type=alert_type.value,
            severity=severity.value,
            message=message,
            context={**(context or {}), "context_key": key},
            is_active=True,
        )
        self.session.add(alert)
        await self.session.flush()
        logger.info("Alert raised [%s] %s", severity.value, message)
        return alert

    async def acknowledge(self, alert_id: str, user: str, note: str | None = None) -> Alert | None:
        alert = await self.get(alert_id)
        if alert is None:
            return None
        alert.acknowledged = True
        alert.acknowledged_by = user
        alert.acknowledged_at = datetime.now(timezone.utc)
        alert.is_active = False
        if note:
            ctx = dict(alert.context or {})
            ctx["acknowledgement_note"] = note
            alert.context = ctx
        await self.session.flush()
        return alert

    async def clear_incident_alerts(self, incident_id: str, reason: str) -> int:
        alerts = list(
            (
                await self.session.scalars(
                    select(Alert).where(
                        Alert.incident_id == incident_id, Alert.is_active.is_(True)
                    )
                )
            ).all()
        )
        now = datetime.now(timezone.utc)
        for alert in alerts:
            alert.is_active = False
            ctx = dict(alert.context or {})
            ctx["resolved_reason"] = reason
            ctx["resolved_at"] = now.isoformat()
            alert.context = ctx
        if alerts:
            await self.session.flush()
        return len(alerts)

    # -- rule-based generation ---------------------------------------------

    async def evaluate_incident(
        self,
        incident: Any,
        *,
        assessment: dict[str, Any] | None = None,
    ) -> list[Alert]:
        """Apply every incident-scoped alert rule to one incident."""
        raised: list[Alert] = []
        iid = getattr(incident, "incident_id", None)

        severity = _value(getattr(incident, "severity_level", ""))
        band = _value(getattr(incident, "severity_level", ""))
        factors = getattr(incident, "priority_factors", None) or {}
        band_severity = (factors.get("unverified_severity") if isinstance(factors, dict) else None)

        # Critical band incidents always alert, even when reported as
        # verification_required, because the *potential* severity matters.
        effective = band_severity or band

        if effective == "critical":
            alert = await self.raise_alert(
                AlertType.CRITICAL_INCIDENT,
                f"CRITICAL incident {iid}: priority score "
                f"{getattr(incident, 'priority_score', 0)} with band severity "
                f"'{effective}'. Immediate coordinator review required.",
                severity=AlertSeverity.CRITICAL,
                incident_id=iid,
                context={
                    "priority_score": getattr(incident, "priority_score", None),
                    "severity": getattr(incident, "severity_level", None),
                    "people_reported_affected": getattr(
                        incident, "people_reported_affected", None
                    ),
                },
            )
            if alert:
                raised.append(alert)

        if assessment:
            escalation = assessment.get("escalation_potential")
            if escalation and escalation != "none":
                alert = await self.raise_alert(
                    AlertType.SEVERITY_ESCALATED,
                    f"Escalation potential for {iid}: {escalation}.",
                    severity=AlertSeverity.WARNING,
                    incident_id=iid,
                    context={"escalation_potential": escalation},
                )
                if alert:
                    raised.append(alert)

            weather = assessment.get("weather") or {}
            if weather.get("worsening") or weather.get("severe_warning"):
                alert = await self.raise_alert(
                    AlertType.WEATHER_WORSENING,
                    f"Weather deteriorating at {iid}: "
                    f"{weather.get('condition', 'unknown condition')}, "
                    f"{weather.get('rainfall_next_6h_mm')}mm forecast rain in 6h"
                    + (" - SEVERE WARNING IN FORCE." if weather.get("severe_warning") else "."),
                    severity=(
                        AlertSeverity.CRITICAL
                        if weather.get("severe_warning")
                        else AlertSeverity.WARNING
                    ),
                    incident_id=iid,
                    context={
                        "simulation_mode": weather.get("simulation_mode"),
                        "worsening": weather.get("worsening"),
                        "severe_warning": weather.get("severe_warning"),
                    },
                )
                if alert:
                    raised.append(alert)

            access = assessment.get("accessibility") or {}
            if access.get("status") in {RouteStatus.CLOSED.value, RouteStatus.IMPASSABLE.value}:
                known = (access.get("known_condition") or {}).get("is_fact")
                alert = await self.raise_alert(
                    AlertType.ROUTE_BLOCKED,
                    f"Access route to {iid} reported {access.get('status')}"
                    + (" (authoritative report)." if known
                       else " (INFERRED - field verification required)."),
                    severity=AlertSeverity.CRITICAL if known else AlertSeverity.WARNING,
                    incident_id=iid,
                    context={
                        "status": access.get("status"),
                        "is_confirmed_fact": known,
                        "verification_required": access.get("verification_required"),
                        "notes": access.get("notes"),
                    },
                )
                if alert:
                    raised.append(alert)

        if getattr(incident, "is_duplicate", False):
            alert = await self.raise_alert(
                AlertType.DUPLICATE_DETECTED,
                f"Potential duplicate report for {iid} "
                f"(similarity {getattr(incident, 'duplicate_similarity', None)}). "
                "Linked for human review - not deleted.",
                severity=AlertSeverity.INFO,
                incident_id=iid,
                context={
                    "duplicate_of": getattr(incident, "duplicate_of", None),
                    "similarity": getattr(incident, "duplicate_similarity", None),
                },
            )
            if alert:
                raised.append(alert)

        return raised

    async def evaluate_shelters(self, shelters: list[Any], threshold: float) -> list[Alert]:
        raised: list[Alert] = []
        for shelter in shelters:
            if not shelter.capacity:
                continue
            pct = shelter.utilization_pct
            if pct >= threshold:
                alert = await self.raise_alert(
                    AlertType.SHELTER_CAPACITY,
                    f"Shelter {shelter.name} ({shelter.shelter_id}) at "
                    f"{pct}% capacity ({shelter.current_occupancy}/"
                    f"{shelter.capacity}, {shelter.available_capacity} places left).",
                    severity=(
                        AlertSeverity.CRITICAL if pct >= 95 else AlertSeverity.WARNING
                    ),
                    context={
                        "shelter_id": shelter.shelter_id,
                        "utilization_pct": pct,
                        "threshold_pct": threshold,
                        "available_capacity": shelter.available_capacity,
                    },
                    context_key=f"shelter_capacity:{shelter.shelter_id}:{int(pct // 5) * 5}",
                )
                if alert:
                    raised.append(alert)
        return raised

    async def evaluate_shortages(self, shortages: list[dict[str, Any]]) -> list[Alert]:
        raised: list[Alert] = []
        for item in shortages:
            if int(item.get("deficit") or 0) <= 0:
                continue
            alert = await self.raise_alert(
                AlertType.RESOURCE_SHORTAGE,
                f"Resource shortage: {item.get('label')} - required "
                f"{item.get('required')}, available {item.get('available')}, "
                f"deficit {item.get('deficit')} {item.get('unit', 'units')}. "
                "Escalation or mutual-aid request required.",
                severity=AlertSeverity.WARNING,
                incident_id=item.get("incident_id"),
                context=item,
                context_key=f"shortage:{item.get('resource_type')}:"
                            f"{item.get('incident_id')}:{item.get('deficit')}",
            )
            if alert:
                raised.append(alert)
        return raised

    async def evaluate_roads(self, roads: list[Any]) -> list[Alert]:
        raised: list[Alert] = []
        for road in roads:
            status = _value(getattr(road, "status", ""))
            fact = _value(getattr(road, "fact_status", ""))
            if status in {RouteStatus.CLOSED.value, RouteStatus.IMPASSABLE.value}:
                alert = await self.raise_alert(
                    AlertType.ROUTE_BLOCKED,
                    f"{road.name} ({road.road_id}) is {status}"
                    + (
                        f" - reported by {road.reported_by}."
                        if getattr(road, "reported_by", None)
                        else "."
                    )
                    + (" [AUTHORITATIVE REPORT]" if fact == "known" else
                       " [INFERRED - verification required]"
                       if fact == "inferred" else " [UNVERIFIED SOURCE]"),
                    severity=AlertSeverity.CRITICAL if fact == "known" else AlertSeverity.WARNING,
                    context={
                        "road_id": road.road_id,
                        "status": status,
                        "fact_status": fact,
                        "blocked_reason": getattr(road, "blocked_reason", None),
                        "origin_zone": getattr(road, "origin_zone", None),
                        "destination_zone": getattr(road, "destination_zone", None),
                    },
                    context_key=f"road:{road.road_id}:{status}",
                )
                if alert:
                    raised.append(alert)
        return raised

    async def evaluate_overdue_actions(self, actions: list[Any], minutes: int) -> list[Alert]:
        raised: list[Alert] = []
        now = datetime.now(timezone.utc)
        for action in actions:
            if _value(getattr(action, "status", "")) not in {"approved", "in_progress"}:
                continue
            reference = getattr(action, "start_time", None) or getattr(action, "created_at", None)
            if reference is None:
                continue
            if reference.tzinfo is None:
                reference = reference.replace(tzinfo=timezone.utc)
            overdue_minutes = (now - reference).total_seconds() / 60.0
            if overdue_minutes < minutes:
                continue
            alert = await self.raise_alert(
                AlertType.ACTION_OVERDUE,
                f"Action {action.action_id} ({action.description[:60]}) is overdue - "
                f"open for {int(overdue_minutes)} minutes (threshold {minutes}).",
                severity=AlertSeverity.WARNING,
                incident_id=getattr(action, "incident_id", None),
                context={
                    "action_id": action.action_id,
                    "overdue_minutes": int(overdue_minutes),
                    "threshold_minutes": minutes,
                },
                context_key=f"overdue:{action.action_id}:{int(overdue_minutes // 30) * 30}",
            )
            if alert:
                raised.append(alert)
        return raised


def _derive_key(
    alert_type: AlertType, incident_id: str | None, context: dict[str, Any] | None
) -> str:
    parts = [alert_type.value, incident_id or "global"]
    for key in sorted((context or {}).keys())[:3]:
        parts.append(f"{key}={context[key]}")
    return "|".join(str(p) for p in parts)


def _value(value: Any) -> str:
    if value is None:
        return ""
    return value.value if hasattr(value, "value") else str(value)